//------------------------------------------------------------------------------
// The sprite rasterizer's two reciprocal ROMs, generated by
// tools/gen_sprite_tables.py (docs/sprite-rasterizer.md). Loaded with
// $readmemh, which both Verilator and Quartus honour for ROM initialisation;
// HEXDIR is set by whoever instantiates this to wherever rtl/data lives
// relative to the tool's working directory.
//------------------------------------------------------------------------------
`default_nettype none

module sprite_tables #(parameter string HEXDIR = "rtl/data") (
    input  logic        clk,
    input  logic  [9:0] zoom_addr,
    output logic [23:0] zoom_q,
    input  logic [10:0] recip_addr,
    output logic [23:0] recip_q
);
    logic [23:0] zoomtab  [1024];
    logic [23:0] reciptab [2048];
    initial begin
        $readmemh({HEXDIR, "/zoom.hex"},  zoomtab);
        $readmemh({HEXDIR, "/recip.hex"}, reciptab);
    end
    always_ff @(posedge clk) begin
        zoom_q  <= zoomtab[zoom_addr];
        recip_q <= reciptab[recip_addr];
    end
endmodule
